import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  ArrowRightLeft,
  Banknote,
  BarChart2,
  BarChart3,
  Bell,
  BellRing,
  BookOpen,
  BookText,
  BookUser,
  Boxes,
  Briefcase,
  Building,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cpu,
  CreditCard,
  Factory,
  FileBarChart,
  FileSignature,
  FileText,
  FolderOpen,
  GitBranch,
  Hammer,
  HandCoins,
  Hash,
  Headphones,
  History,
  IdCard,
  Kanban,
  Landmark,
  Layers,
  LayoutDashboard,
  LineChart,
  Package,
  PackageCheck,
  Phone,
  PiggyBank,
  Receipt,
  ReceiptText,
  Scale,
  ScanBarcode,
  ScanLine,
  ScrollText,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Truck,
  Undo,
  Undo2,
  UserCog,
  UserPlus,
  Users,
  Users2,
  Wallet,
  Warehouse,
  Workflow,
} from "lucide-react";

export const NAV_ICONS = {
  layoutDashboard: LayoutDashboard,
  users: Users,
  shield: Shield,
  bell: Bell,
  activity: Activity,
  building2: Building2,
  creditCard: CreditCard,
  settings: Settings,
  boxes: Boxes,
  shoppingCart: ShoppingCart,
  fileText: FileText,
  barChart3: BarChart3,
  sparkles: Sparkles,
  package: Package,
  userCog: UserCog,
  briefcase: Briefcase,
  idCard: IdCard,
  calendarCheck: CalendarCheck,
  calendarDays: CalendarDays,
  wallet: Wallet,
  banknote: Banknote,
  target: Target,
  userPlus: UserPlus,
  phone: Phone,
  kanban: Kanban,
  fileSignature: FileSignature,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  bookUser: BookUser,
  handCoins: HandCoins,
  headphones: Headphones,
  bellRing: BellRing,
  lineChart: LineChart,
  clock: Clock,
  calendarRange: CalendarRange,
  timer: Timer,
  star: Star,
  folderOpen: FolderOpen,
  history: History,
  scrollText: ScrollText,
  bookOpen: BookOpen,
  bookText: BookText,
  scale: Scale,
  trendingUp: TrendingUp,
  receipt: Receipt,
  landmark: Landmark,
  arrowRightLeft: ArrowRightLeft,
  fileBarChart: FileBarChart,
  piggyBank: PiggyBank,
  receiptText: ReceiptText,
  warehouse: Warehouse,
  hash: Hash,
  scanBarcode: ScanBarcode,
  layers: Layers,
  calendarClock: CalendarClock,
  alertTriangle: AlertTriangle,
  truck: Truck,
  shoppingBag: ShoppingBag,
  packageCheck: PackageCheck,
  undo2: Undo2,
  building: Building,
  barChart2: BarChart2,
  factory: Factory,
  hammer: Hammer,
  cpu: Cpu,
  shieldCheck: ShieldCheck,
  trash2: Trash2,
  gitBranch: GitBranch,
  workflow: Workflow,
  store: Store,
  scanLine: ScanLine,
  undo: Undo,
  checkSquare: CheckSquare,
  users2: Users2,
} as const satisfies Record<string, LucideIcon>;

export type NavIconName = keyof typeof NAV_ICONS;

export function getNavIcon(name: NavIconName): LucideIcon {
  return NAV_ICONS[name] ?? LayoutDashboard;
}
